### PR TITLE
Changed assertion to proper case handling, Fixes #36

### LINKED ISSUE #36: Failed assertion missed due to Release mode
https://github.com/MEPP-team/MEPP2/blob/f0651ed0874c3287ad1b3b0a113b83905c8dcc47/FEVV/Filters/Generic/mesh_from_vector_representation.hpp#L686

I have a mesh which fails the assertion above.
PR is comming

### PR DESCRIPTION
**Pull request by Aelphy**

### CODE REVIEW

**Review by elombardi2 — COMMENTED** [review]
Thanks to point out `CGAL::Euler::can_add_face`. It's too early for the projet to use it because we want to be compatible with CGAL 4.14, which doesn't implement this function.

As far as I understand the other changes, the main change is to replace the `assert` line [here](https://github.com/MEPP-team/MEPP2/blob/f0651ed0874c3287ad1b3b0a113b83905c8dcc47/FEVV/Filters/Generic/mesh_from_vector_representation.hpp#L686).
The proposed changes bring two fixes:
- the validity test of `current_face` is done in Debug AND Release mode (currently only done in Debug mode)
- if `current_face` is not valid, the face is safely ignored and the code jumps to the next face ; currently, in debug mode, the program stops due to an assertion error ; currently, in release mode, the program continues with `current_face` containing an invalid value, and crashes later.

I suggest to rewrite the fixes with this in mind, without using `CGAL::Euler::can_add_face`. I will do it.

**Comment by Aelphy** [comment]
Thank you for your reply.

You are absolutely right.
please let me know if I can help.

PS

I found another issue, that if original and corrupted meshes are interchanged, there is another assert violation from CGAL / segfault [here](https://github.com/MEPP-team/MEPP2/blob/c53ae208e2c30c428049bb23c7e13e5a092c7916/FEVV/Filters/CGAL/Surface_mesh/msdm2.h#L626)
with the following error:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: _idx < data_.size()
```

The reason is still unclear to me. When changing the order of meshes back to original first, corrupted second the problem is not occurring anymore.

**Comment by elombardi2** [comment]
Please could you open a separate issue for the second problem?

**Comment by elombardi2** [comment]
[This commit](https://github.com/elombardi2/MEPP2/commit/03189b999f2d4463793e8f10c045b7e26ce9d17e), inspired by the present PR, should fix issue #37.
Could you test and give me a feedback?

**Comment by Aelphy** [comment]
Checked, LGTM

**Pull request closed without merging**
